# Generated by Django 5.1.4 on 2025-11-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0008_alter_video_image_file_alter_video_video_file'),
        ('users_app', '0003_alter_userprofile_favorite_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Optional address for the user (up to 120 characters).', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, help_text='Videos marked as favorites by the user.', related_name='users', to='content_app.video'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number for the user.', max_length=20, null=True),
        ),
    ]
