# Generated by Django 5.1.4 on 2025-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_video_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='converted_files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
