# Generated by Django 5.1.4 on 2025-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_video_converted_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='converted_files',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
