# Generated by Django 5.1.4 on 2025-01-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0005_video_category_alter_video_converted_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Philosophical', 'Philosophical'), ('Political', 'Political'), ('Romance', 'Romance'), ('Science fiction', 'Science fiction'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Biographical', 'Biographical'), ('Educational', 'Educational'), ('Erotic', 'Erotic'), ('Musical', 'Musical'), ('Reality', 'Reality'), ('Sports', 'Sports'), ('Superhero', 'Superhero'), ('Surreal', 'Surreal'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='converted_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
