# Generated by Django 5.1.4 on 2025-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_alter_video_options_alter_video_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='converted_files',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
