# Generated by Django 5.1.4 on 2025-10-05 10:43

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_alter_video_converted_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='videos'),
        ),
    ]
