# Generated by Django 5.1.4 on 2025-11-16 09:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0008_alter_video_image_file_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='converted_files',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\User\\Desktop\\Backend\\videoflix-backend\\uploads'), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\User\\Desktop\\Backend\\videoflix-backend\\uploads'), upload_to='videos/'),
        ),
    ]
