# Generated by Django 5.1.4 on 2025-11-16 12:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0009_alter_video_converted_files_alter_video_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_file',
            field=models.ImageField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\User\\Desktop\\Backend\\videoflix-backend\\uploads'), upload_to='images/'),
        ),
    ]
