# Generated by Django 5.1.4 on 2025-11-22 16:23

import content_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0010_alter_video_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Last processing error message, if any.', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Background processing state (transcoding, thumbnail, etc.).', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\User\\Desktop\\Backend\\videoflix-backend\\uploads'), upload_to='videos/', validators=[content_app.models.validate_video_file_size]),
        ),
    ]
