# Generated by Django 5.1.4 on 2025-11-22 20:49

import content_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0011_video_processing_error_video_processing_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='processing_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Background processing state.', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\User\\Desktop\\Backend\\videoflix-backend\\uploads'), upload_to='videos/', validators=[content_app.models.validate_video_file_size]),
        ),
    ]
